name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Branch
      run: echo "${{ steps.branch-name.outputs.current_branch }}"
    - name: runhello
      run: ./hellow
      
  
